import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F7F9FC',
    },
    headerPadding: {
        paddingHorizontal: 20,
        paddingTop: 15,
        paddingBottom: 10,
    },
    mainTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: '#1A1C1E',
    },
    statsText: {
        fontSize: 14,
        color: '#6C757D',
        marginTop: 4,
        fontWeight: '600',
    },
    filterRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 15,
        gap: 10,
    },
    datePickerBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF',
        height: 45,
        borderRadius: 12,
        paddingHorizontal: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
    },
    dateText: {
        marginLeft: 8,
        fontSize: 13,
        color: '#495057',
        fontWeight: '600',
    },
    dropdown: {
        flex: 1,
        backgroundColor: '#FFF',
        height: 45,
        borderRadius: 12,
        paddingHorizontal: 12,
        elevation: 2,
    },
    dropdownPlaceholder: { fontSize: 13, color: '#ADB5BD' },
    dropdownSelected: { fontSize: 13, fontWeight: '600', color: '#37905f' },
    card: {
        backgroundColor: '#FFF',
        marginHorizontal: 20,
        marginBottom: 12,
        borderRadius: 16,
        padding: 16,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    avatar: {
        width: 44,
        height: 44,
        borderRadius: 12,
    },
    headerInfo: {
        flex: 1,
        marginLeft: 12,
    },
    studentName: {
        fontSize: 16,
        fontWeight: '700',
        color: '#212529',
    },
    statusBadge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 6,
        marginTop: 4,
    },
    completedBadge: { backgroundColor: '#E8F5E9' },
    missedBadge: { backgroundColor: '#FFEBEE' },
    statusText: { fontSize: 10, fontWeight: '800' },
    completedText: { color: '#2E7D32' },
    missedText: { color: '#C62828' },
    ratingBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFBE6',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#FFE58F',
    },
    ratingText: {
        marginLeft: 4,
        fontSize: 12,
        fontWeight: '700',
        color: '#876800',
    },
    detailsContainer: {
        flexDirection: 'row',
        backgroundColor: '#F8F9FA',
        padding: 10,
        borderRadius: 10,
        justifyContent: 'space-between',
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    detailText: {
        marginLeft: 6,
        fontSize: 12,
        color: '#495057',
        fontWeight: '500',
    },
    footerSection: {
        marginTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#F1F3F5',
        paddingTop: 10,
    },
    noteLine: {
        flexDirection: 'row',
        marginBottom: 4,
    },
    noteLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: '#6C757D',
    },
    noteText: {
        fontSize: 12,
        color: '#495057',
        flex: 1,
    },
    emptyState: {
        alignItems: 'center',
        marginTop: 80,
        opacity: 0.5,
    },
    emptyText: {
        marginTop: 10,
        fontSize: 16,
    }
});