//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public Enrollment()
        {
            this.TimeTables = new HashSet<TimeTable>();
        }
    
        public int enrollmentid { get; set; }
        public int currentayat { get; set; }
        public string enrollment_status { get; set; }
    
        public virtual StudentTutorRequest StudentTutorRequest { get; set; }
        public virtual User User { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual surah surah { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<TimeTable> TimeTables { get; set; }
    }
}
