//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int progressid { get; set; }
        public int startAyat { get; set; }
        public int endAyat { get; set; }
        public string notes { get; set; }
    
        public virtual TimeTable TimeTable { get; set; }
    }
}
