//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public TimeTable()
        {
            this.Progresses = new HashSet<Progress>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int TimeTableid { get; set; }
        public int startIndex { get; set; }
        public int endIndex { get; set; }
        public string Status { get; set; }
        public System.DateTime ClassDate { get; set; }
        public string Corrections { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual ICollection<Progress> Progresses { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual Slot Slot { get; set; }
    }
}
