//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public TimeTable()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int ClassID { get; set; }
        public string Status { get; set; }
        public string Corrections { get; set; }
        public System.DateTime ClassDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int Surahid { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual LessonPlan LessonPlan { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual Slot Slot { get; set; }
        public virtual StudentTutorRequest StudentTutorRequest { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
