import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F7F9FB',
    },
    pageHeader: {
        paddingHorizontal: 20,
        paddingVertical: 15,
        backgroundColor: '#FFF',
    },
    mainTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: '#1A1C1E',
    },
    statsSummary: {
        fontSize: 14,
        color: '#6C757D',
        marginTop: 4,
    },
    filterBar: {
        flexDirection: 'row',
        paddingHorizontal: 15,
        paddingVertical: 12,
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    datePickerBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF',
        paddingHorizontal: 12,
        height: 40,
        borderRadius: 10,
        elevation: 2,
        width: '45%',
    },
    dateText: {
        marginLeft: 8,
        fontSize: 13,
        color: '#495057',
        fontWeight: '600',
    },
    dropdown: {
        width: '50%',
        height: 40,
        backgroundColor: '#FFF',
        borderRadius: 10,
        paddingHorizontal: 12,
        elevation: 2,
    },
    card: {
        backgroundColor: '#FFF',
        marginHorizontal: 10,
        marginBottom: 15,
        borderRadius: 16,
        padding: 16,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    avatar: {
        width: 48,
        height: 48,
        borderRadius: 14,
        backgroundColor: '#F0F0F0',
    },
    tutorInfo: {
        flex: 1,
        marginLeft: 12,
    },
    tutorName: {
        fontSize: 16,
        fontWeight: '700',
        color: '#212529',
    },
    statusBadge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 6,
        marginTop: 4,
    },
    completedBadge: { backgroundColor: '#E8F5E9' },
    missedBadge: { backgroundColor: '#FFEBEE' },
    statusText: { fontSize: 10, fontWeight: '800' },
    completedText: { color: '#2E7D32' },
    missedText: { color: '#C62828' },
    ratingBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF9E6',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    ratingNumber: {
        marginLeft: 4,
        fontSize: 12,
        fontWeight: '700',
        color: '#FF8C00',
    },
    detailsGrid: {
        flexDirection: 'row',
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: '#F1F3F5',
        paddingVertical: 10,
        justifyContent: 'space-between',
    },
    detailItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    detailValue: {
        marginLeft: 6,
        fontSize: 13,
        color: '#495057',
        fontWeight: '500',
    },
    assignmentBox: {
        marginTop: 12,
        backgroundColor: '#F8F9FA',
        padding: 10,
        borderRadius: 8,
    },
    assignmentLabel: {
        fontSize: 11,
        fontWeight: '700',
        color: '#6C757D',
        marginBottom: 4,
    },
    assignmentContent: {
        fontSize: 13,
        color: '#212529',
        lineHeight: 18,
    },
    emptyContainer: {
        alignItems: 'center',
        marginTop: 100,
    },
    emptyText: {
        marginTop: 10,
        color: '#ADB5BD',
        fontSize: 15,
    },
    placeholderStyle: { fontSize: 13, color: '#ADB5BD' },
    selectedTextStyle: { fontSize: 13, color: '#495057', fontWeight: '600' },
    icon: { marginRight: 8 },
});